#!/bin/bash

set -ex

source "$(dirname "$0")/lib/pkg.sh"

pkg_update

case "$OS" in
    arch)
        pkg_install vim htop tmux git python-pip ruby samba jq curl zsh
        ;;
    *)
        pkg_install vim htop tmux git python3-pip ruby-full samba jq curl zsh
        ;;
esac

chsh -s /bin/zsh

bash install-ohmyzsh
bash install-rust
bash config-python
bash config-tmux
bash install-java
bash install-nerdfonts
bash install-nvim

cp -r .config "${HOME}"
