#!/bin/bash

source "$(dirname "$0")/lib/pkg.sh"

pkg_install fontconfig

# Install icon fonts (OS-specific package names)
case "$OS" in
    arch)
        sudo pacman -S --needed --noconfirm ttf-font-awesome
        ;;
esac

NERD_FONTS_TMP=$(mktemp -d)
trap "rm -rf $NERD_FONTS_TMP" EXIT
git clone https://github.com/ryanoasis/nerd-fonts.git "$NERD_FONTS_TMP"
(cd "$NERD_FONTS_TMP" && bash install.sh)
fc-cache -f -v
