#!/bin/bash

source "$(dirname "$0")/lib/pkg.sh"

case "$OS" in
    arch)
        if [[ "x86_64" == "$(uname -p)" ]]; then
            aur_install msr-tools
        fi
        pkg_install base-devel cmake libuv openssl hwloc
        ;;
    *)
        if [[ "x86_64" == "$(uname -p)" ]]; then
            pkg_install ubuntu-drivers-common msr-tools
        fi
        pkg_install build-essential cmake libuv1-dev libssl-dev libhwloc-dev
        ;;
esac

NPROC=$(nproc)

mkdir -p $HOME/workspace

git clone https://github.com/xmrig/xmrig.git $HOME/workspace/xmrig

mkdir -p $HOME/workspace/xmrig/build
(cd $HOME/workspace/xmrig/scripts && sudo ./randomx_boost.sh)
(cd $HOME/workspace/xmrig/scripts && sudo ./build_deps.sh)
(cd $HOME/workspace/xmrig/build && cmake .. -DXMRIG_DEPS=scripts/deps)
(cd $HOME/workspace/xmrig/build && make -j$NPROC)
