#!/bin/bash

set -ex

mkdir -p /tmp/vscode

wget https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64 -O /tmp/vscode/vscode.deb
sudo apt install -y /tmp/vscode/vscode.deb

rm -rf /tmp/vscode
