#!/bin/bash

source "$(dirname "$0")/lib/pkg.sh"

if [ -d "$HOME/.oh-my-zsh" ]; then
    cp config/robbyrussell.zsh-theme "${HOME}/.oh-my-zsh/themes/"
    exit 0
fi

pkg_install zsh curl

export KEEP_ZSHRC="yes"
# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
cp config/robbyrussell.zsh-theme "${HOME}/.oh-my-zsh/themes/"
