#!/bin/bash

if [ -d "$HOME/.oh-my-zsh" ]; then
    exit 0
fi


sudo apt install -y zsh curl

# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
