#!/bin/bash

source "$(dirname "$0")/lib/pkg.sh"

pkg_install fontconfig

# Install icon fonts (OS-specific package names)
case "$OS" in
    arch)
        sudo pacman -S --needed --noconfirm ttf-font-awesome
        ;;
esac

git clone https://github.com/ryanoasis/nerd-fonts.git
trap 'rm -rf nerd-fonts' EXIT
(cd nerd-fonts; bash install.sh)
fc-cache -f -v
