#!/bin/bash

set -e

source "$(dirname "$0")/../lib/pkg.sh"

case "$OS" in
    arch)
        pkg_install waybar fzf pacman-contrib networkmanager
        ;;
esac

sudo systemctl enable --now NetworkManager
